name: "Release"
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: latest
          run_install: true
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 18.x
          cache: "pnpm"
      - name: Build the extension
        run: pnpm build
      - name: Package the extension into a zip artifact
        run: pnpm package
      - name: Rename zip
        run: mv build/chrome-mv3-prod.zip mermaid-previewer.zip
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: mermaid-previewer.zip
